export const GIT_VERSION = 'git --version'
export const GET_REV_PARSE = 'git rev-parse HEAD'
export const GIT_BRANCH= 'git branch --show-current'
export const GET_CHECKOUT = 'git checkout '
export const GIT_STATUS = 'git status '
export const GIT_ADD = 'git add '
export const GIT_COMMIT = 'git commit -m '
export const GIT_MERGE = 'git merge '
export const GIT_DELETE_BRANCH = 'git branch -D '
export const GIT_HEAD = 'git rev-parse HEAD'
export const GIT_LOG = 'git log --pretty=oneline --reverse '
