export declare const GIT_VERSION = "git --version";
export declare const GET_REV_PARSE = "git rev-parse HEAD";
export declare const GIT_BRANCH = "git branch --show-current";
export declare const GET_CHECKOUT = "git checkout ";
export declare const GIT_STATUS = "git status ";
export declare const GIT_ADD = "git add ";
export declare const GIT_COMMIT = "git commit -m ";
export declare const GIT_MERGE = "git merge ";
export declare const GIT_DELETE_BRANCH = "git branch -D ";
export declare const GIT_HEAD = "git rev-parse HEAD";
export declare const GIT_LOG = "git log --pretty=oneline --reverse ";
