"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GIT_LOG = exports.GIT_HEAD = exports.GIT_DELETE_BRANCH = exports.GIT_MERGE = exports.GIT_COMMIT = exports.GIT_ADD = exports.GIT_STATUS = exports.GET_CHECKOUT = exports.GIT_BRANCH = exports.GET_REV_PARSE = exports.GIT_VERSION = void 0;
exports.GIT_VERSION = 'git --version';
exports.GET_REV_PARSE = 'git rev-parse HEAD';
exports.GIT_BRANCH = 'git branch --show-current';
exports.GET_CHECKOUT = 'git checkout ';
exports.GIT_STATUS = 'git status ';
exports.GIT_ADD = 'git add ';
exports.GIT_COMMIT = 'git commit -m ';
exports.GIT_MERGE = 'git merge ';
exports.GIT_DELETE_BRANCH = 'git branch -D ';
exports.GIT_HEAD = 'git rev-parse HEAD';
exports.GIT_LOG = 'git log --pretty=oneline --reverse ';
